services:

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ja_admin
      POSTGRES_PASSWORD: securepass
      POSTGRES_DB: ja_clients
    ports:
      - "5432:5432"
      - "15432:5432" #extra port for local testing/debug

    volumes:
      - pgdata:/var/lib/postgresql/data
      
      # issue-apr-2025✅ Override pg_hba.conf to allow host-based password auth (fix pgweb access issue)
      #- ./pg_config/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
      
      # issue-apr-2025✅ Custom postgresql.conf to allow external connections (listen_addresses='*')
      #- ./pg_config/postgresql.conf:/var/lib/postgresql/data/postgresql.conf

    # issue-apr-2025✅ Force PostgreSQL to use our custom postgresql.conf on startup
    #command: postgres -c config_file=/var/lib/postgresql/data/postgresql.conf



  superset:
    build:
      context: .
      dockerfile: Dockerfile.superset
    ports:
      - "8088:8088"
    environment:
      - SUPERSET_SECRET_KEY=supersecretkey123
    volumes:
      - ./superset_home:/app/superset_home
    depends_on:
      - db

  pgweb:
    image: sosedoff/pgweb
    restart: always
    ports:
      - "8081:8081"
    environment:
      - PGWEB_DATABASE_URL=postgres://ja_admin:securepass@db:5432/ja_clients?sslmode=disable
    depends_on:
      - db


  automation:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
    command: bash -c "python3 automation_python_ja_db_02_autocommit_helper_server.py & python3 automation_python_ja_db_02_sync_action_helper_server.py & python3 automation_python_ja_db_02_autosyncbackto_googledrive_helper.py & wait"
    
  flink-jobmanager:
    image: flink:1.17
    restart: always
    ports:
      - "8082:8081"  # Flink Web UI
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
    command: jobmanager
    depends_on:
      - db

  flink-taskmanager:
    image: flink:1.17
    restart: always
    depends_on:
      - flink-jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
    command: taskmanager



volumes:
  pgdata: {}


