services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ja_admin
      POSTGRES_PASSWORD: securepass
      POSTGRES_DB: ja_clients
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

